version: '3'
services:
  webserver:
    container_name: webserver
    image: welrikyson/laravel
    volumes:
      - ./app:/app
    links:
      - database
    ports:
      - 8080:80
  database:
    container_name: database
    restart: always
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: homestead
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database:/var/lib/postgresql